import React from 'react';

const InvestmentOpportunities = () => {
  return (
    <div className="container">
      <h1 className="text-center">Investment Opportunities</h1>
      <div className="row">
        <div className="col-md-12">
          <h2>Aquo's Management Platform for Fractional Ownership and Investment</h2>
          <p className="lead">
            At Aquo, we offer a comprehensive management platform that enables you to participate in fractional ownership and invest in a variety of assets, including real estate and Special Purpose Vehicles (SPVs). Our platform allows you to access the benefits of asset tokenization, providing liquidity and diversification in your investment portfolio.
          </p>
	   <div className="text-center">
        <img src="/houses.jpg" alt="Vision Image" className="img-fluid" style={{ height: "400px" }} />
      </div>
          <h3>Fractional Ownership and Asset Tokenization:</h3>
          <p className="lead">
            Through our platform, you can buy fractional shares in real estate properties and SPVs. Fractional ownership allows you to own a portion of these assets, providing you with exposure to their value and potential profits. Asset tokenization converts these assets into digital representations, making them easily tradable and divisible.
          </p>
          <h3>Real Estate Investments:</h3>
          <p className="lead">
            With Aquo, you can invest in real estate properties without the need for significant capital. By purchasing fractional shares, you gain access to the potential income generated from rents and the appreciation of the property's value. This allows you to diversify your investment portfolio and participate in the real estate market with ease.
          </p>
          <h3>Special Purpose Vehicles (SPVs):</h3>
          <p className="lead">
            SPVs are entities created for specific investment purposes. Our platform enables you to invest in fractional shares of SPVs, providing you with opportunities in sectors such as infrastructure, energy, and technology. By investing in SPVs, you can diversify your portfolio across various industries and potentially benefit from the profits generated by these entities.
          </p>
          <h3>Profits and Income:</h3>
          <p className="lead">
            When you invest through Aquo, you have the potential to earn profits and income from your investments. In the case of real estate properties, you can receive rental income based on your fractional ownership. Additionally, as SPVs generate profits, you may be entitled to a portion of those earnings, offering you a source of potential income.
          </p>
          <h3>Aquo's Management Platform:</h3>
          <p className="lead">
            Our platform serves as a comprehensive management tool for your investments. We provide a user-friendly interface that allows you to track and manage your fractional ownership in real estate properties and SPVs. You can monitor the performance of your investments, access financial statements, and stay informed about any updates related to your holdings.
          </p>
        </div>
      </div>
    </div>
  );
};

export default InvestmentOpportunities;

